version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./redteam:/app/redteam
      - ./evaluation:/app/evaluation
      - ./app:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
# Add your observability stack (ELK/Grafana) here later as separate services.
